"""Initial schema with all models and Stripe billing

Revision ID: 8d9ffe30ec40
Revises: 
Create Date: 2026-03-04 19:14:18.178972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d9ffe30ec40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('monthly_synthesis_quota', sa.Integer(), nullable=False),
    sa.Column('current_month_usage', sa.Integer(), nullable=False),
    sa.Column('voices_contributed', sa.Integer(), nullable=False),
    sa.Column('has_contributed_voice', sa.Boolean(), nullable=False),
    sa.Column('voice_consent_granted', sa.Boolean(), nullable=False),
    sa.Column('voice_consent_updated_at', sa.DateTime(), nullable=True),
    sa.Column('current_free_period_end', sa.DateTime(), nullable=True),
    sa.Column('free_periods_used', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('subscription_status', sa.String(), nullable=False),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('current_month_usage_characters', sa.Integer(), nullable=False),
    sa.Column('current_month_cost_cents', sa.Integer(), nullable=False),
    sa.Column('total_spent_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_api_key'), 'users', ['api_key'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=True)
    op.create_index(op.f('ix_users_stripe_subscription_id'), 'users', ['stripe_subscription_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('hashed_key', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('requests_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_hashed_key'), 'api_keys', ['hashed_key'], unique=True)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('free_trial_grants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('grant_reason', sa.String(), nullable=False),
    sa.Column('related_voice_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('bonus_monthly_quota', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_free_trial_grants_user_id'), 'free_trial_grants', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=False),
    sa.Column('stripe_price_id', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_period_start', sa.DateTime(), nullable=False),
    sa.Column('current_period_end', sa.DateTime(), nullable=False),
    sa.Column('renewal_attempts', sa.Integer(), nullable=False),
    sa.Column('monthly_character_limit', sa.Integer(), nullable=False),
    sa.Column('monthly_price_cents', sa.Integer(), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('voices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('accent', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('speaker_embedding', sa.LargeBinary(), nullable=False),
    sa.Column('embedding_model', sa.String(), nullable=False),
    sa.Column('sample_urls', sa.String(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('total_characters_synthesized', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voices_name'), 'voices', ['name'], unique=False)
    op.create_index(op.f('ix_voices_owner_id'), 'voices', ['owner_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('subscription_id', sa.String(), nullable=False),
    sa.Column('stripe_invoice_id', sa.String(), nullable=False),
    sa.Column('stripe_status', sa.String(), nullable=False),
    sa.Column('base_amount', sa.Integer(), nullable=False),
    sa.Column('usage_amount', sa.Integer(), nullable=False),
    sa.Column('tax_amount', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('invoice_pdf_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_stripe_invoice_id'), 'invoices', ['stripe_invoice_id'], unique=True)
    op.create_index(op.f('ix_invoices_user_id'), 'invoices', ['user_id'], unique=False)
    op.create_table('synthesis_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('voice_id', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('text_hash', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('style', sa.String(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('pitch', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('audio_url', sa.String(), nullable=True),
    sa.Column('audio_duration', sa.Float(), nullable=True),
    sa.Column('cache_key', sa.String(), nullable=True),
    sa.Column('is_cached', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('inference_time_ms', sa.Float(), nullable=True),
    sa.Column('total_time_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['voice_id'], ['voices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_synthesis_jobs_status'), 'synthesis_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_synthesis_jobs_text_hash'), 'synthesis_jobs', ['text_hash'], unique=False)
    op.create_index(op.f('ix_synthesis_jobs_user_id'), 'synthesis_jobs', ['user_id'], unique=False)
    op.create_index(op.f('ix_synthesis_jobs_voice_id'), 'synthesis_jobs', ['voice_id'], unique=False)
    op.create_table('voice_contributions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('voice_id', sa.String(), nullable=False),
    sa.Column('voice_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('consent_granted', sa.Boolean(), nullable=False),
    sa.Column('consent_version', sa.String(), nullable=False),
    sa.Column('times_used_in_training', sa.Integer(), nullable=False),
    sa.Column('times_synthesized', sa.Integer(), nullable=False),
    sa.Column('free_period_awarded', sa.Boolean(), nullable=False),
    sa.Column('free_period_grant_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['free_period_grant_id'], ['free_trial_grants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['voice_id'], ['voices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_contributions_user_id'), 'voice_contributions', ['user_id'], unique=False)
    op.create_index(op.f('ix_voice_contributions_voice_id'), 'voice_contributions', ['voice_id'], unique=False)
    op.create_table('voice_samples',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('voice_id', sa.String(), nullable=False),
    sa.Column('audio_url', sa.String(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('sample_rate', sa.Integer(), nullable=False),
    sa.Column('transcript', sa.String(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['voice_id'], ['voices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_samples_voice_id'), 'voice_samples', ['voice_id'], unique=False)
    op.create_table('usage_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('invoice_id', sa.String(), nullable=True),
    sa.Column('synthesis_job_id', sa.String(), nullable=True),
    sa.Column('stripe_subscription_item_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.Column('total_cost_cents', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_events_user_id'), 'usage_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_events_user_id'), table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_index(op.f('ix_voice_samples_voice_id'), table_name='voice_samples')
    op.drop_table('voice_samples')
    op.drop_index(op.f('ix_voice_contributions_voice_id'), table_name='voice_contributions')
    op.drop_index(op.f('ix_voice_contributions_user_id'), table_name='voice_contributions')
    op.drop_table('voice_contributions')
    op.drop_index(op.f('ix_synthesis_jobs_voice_id'), table_name='synthesis_jobs')
    op.drop_index(op.f('ix_synthesis_jobs_user_id'), table_name='synthesis_jobs')
    op.drop_index(op.f('ix_synthesis_jobs_text_hash'), table_name='synthesis_jobs')
    op.drop_index(op.f('ix_synthesis_jobs_status'), table_name='synthesis_jobs')
    op.drop_table('synthesis_jobs')
    op.drop_index(op.f('ix_invoices_user_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_stripe_invoice_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_voices_owner_id'), table_name='voices')
    op.drop_index(op.f('ix_voices_name'), table_name='voices')
    op.drop_table('voices')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_customer_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_free_trial_grants_user_id'), table_name='free_trial_grants')
    op.drop_table('free_trial_grants')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_hashed_key'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_stripe_subscription_id'), table_name='users')
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_api_key'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
